### ISSUE TITLE
Alexandria

### ISSUE THREAD

**Issue by PrinzAxel** [SilverpointDev/sptbxlib#100]
Just wondering if there's a specifics for installing for Delphi 11 Alexandria.

**Comment by pyscripter** [comment]
There is just one set of packages that can be installed with any Delphi version including Alexandria.

**Comment by PrinzAxel** [comment]
When I tried it with Alexandria, there wasn't any identification of Delphi 11 - so I repeated it on a machine with 10.4.2 and that did show up.
