### ISSUE TITLE
can not compile Demo\Overview\Overview.dpr

### ISSUE THREAD

**Issue by mksjgj** [SilverpointDev/sptbxlib#102]
Delphi 10.3(Rio)
error: [dcc32 Error] SpTBXImageList.pas(112): E2003 Undeclared identifier: 'Add'

procedure SpLoadGlyphs(IL: TCustomImageList; GlyphPath: string);
// Finds png files on GlyphPath and adds them to IL
// If IL is a TVirtualImageList it adds all the PNGs sizes.
// Otherwise it adds only the PNGs that matches the size of the IL
// Notation of files must be filename-16x16.png
var
  Files: TStringDynArray;
  FilenameS, S, ILSize: string;
  I: Integer;
  P: TPngImage;
  B: TBitmap;
begin
  ILSize := Format('%dX%d', [IL.Width, IL.Height]);
  Files := TDirectory.GetFiles(GlyphPath, '*.png');
  TArray.Sort<string>(Files, TStringComparer.Ordinal);

  for S in Files do begin
    {$IF CompilerVersion >= 33} // for Delphi Rio and up
    // TImageCollection and TVirtualImagelist introduced on Rio
    if IL is TVirtualImageList then begin
      if Assigned(TVirtualImageList(IL).ImageCollection) and (TVirtualImageList(IL).ImageCollection is TImageCollection) then begin
        FilenameS := TPath.GetFileName(S);
        I := LastDelimiter('-_', FilenameS);
        if I > 1 then
          FilenameS := Copy(FilenameS, 1, I-1);
        // Add all the sizes of the png with 1 name on ImageCollection
        TImageCollection(TVirtualImageList(IL).ImageCollection).Add(FilenameS, S);   ----> error is here!
      end;
    end
    else
    {$IFEND}
    begin
      // Try to add only PNGs with the same size as the Image List
      // Notation of files must be filename-16x16.png
      FilenameS := TPath.GetFileNameWithoutExtension(S);
      I := LastDelimiter('-_', FilenameS) + 1;
      if I > 2 then begin
        FilenameS := Copy(FilenameS, I, Length(ILSize));
        if UpperCase(FilenameS) <> ILSize then
          FilenameS := '';
      end;
      if FilenameS <> '' then begin
        P := TPNGImage.Create;
        B := TBitmap.Create;
        try
          P.LoadFromFile(S);
          B.Assign(P);
          IL.ColorDepth := cd32Bit;
          IL.Add(B, nil);
        finally
          P.Free;
          B.Free;
        end;
      end;
    end;
  end;

  {$IF CompilerVersion >= 33} // for Delphi Rio and up
  if IL is TVirtualImageList then
    TVirtualImageList(IL).AutoFill := True;
  {$IFEND}
end;

**Comment by SilverpointDev** [comment]
Fixed
