### ISSUE TITLE
TSpTBXLabelItem.Alignment has no effect

### ISSUE THREAD

**Issue by mksjgj** [SilverpointDev/sptbxlib#103]
put a TSpTBXPopupMenu on a empty form, set it property as following,
then set Form1.PopupMenu to SpTBXPopupMenu1,
run the application,
you will see, The caption of SpTBXLabelItem1 is center, not taLeftJustify
the caption of SpTBXItem1 is  taLeftJustify, not taRightJustify

object SpTBXPopupMenu1: TSpTBXPopupMenu
    Left = 160
    Top = 96
    object SpTBXLabelItem1: TSpTBXLabelItem
      Caption = ' 123'
    end
    object SpTBXItem1: TSpTBXItem
      Caption = 'Hello'
      Alignment = taRightJustify
    end
    object SpTBXItem2: TSpTBXItem
      Caption = 'BASE TEXT'
    end
  end

**Comment by mksjgj** [comment]
Delphi 10.3.3, Windows 10.0.19043.1889

**Comment by SilverpointDev** [comment]
This is as designed, the Alignment property has no effect when the item is on a menu or popupmenu
