### ISSUE TITLE
Current tab goes out of view when restoring a minimized application

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#105]
As per title.  Only happens if the application was maximized before minimizing.

See the video at https://github.com/pyscripter/pyscripter/issues/1172 to get the idea.

**Comment by SilverpointDev** [comment]
Try this, override TSpTBXCustomTabSet.Resize method:

```delphi
procedure TSpTBXCustomTabSet.Resize;
begin
  inherited;
  // Make the selected tab always visible, make it an option?
  if not TabAutofit then
    MakeVisible(ActiveTab);
end;
```

**Comment by pyscripter** [comment]
Thank you!

Making it optional is probably best, since the standard Tab control does not do that.

A couple of issues:
- Still not sure why tabs are shifted when restoring from minimized state.  Why don't they stay as before the minimized state.
- When you shift from maximized to normal state the above code (TSpTBXCustomTabSet.Resize) is triggered twice but the active tab is still hidden.

**Comment by SilverpointDev** [comment]
Fixed, try the latest commit.
Added ActiveTabVisibleOnResize property

**Comment by pyscripter** [comment]
> RightAlignItems is called when the Dock/Toolbar is resized.

You are right.  However I see this when I restore my app from maximized state:

![image](https://github.com/SilverpointDev/sptbxlib/assets/1311616/fc0ca635-1fe7-4adb-891c-3a02d60ae8f5)

The call sequence is:
1. procedure TSpTBXDock.Resize;
2. TSpTBXTabToolbar.RightAlignItems
3. TSpTBXTabToolbar.Resize

Only happens when restoring from maximized, not when resizing.   Looks like a side-effect of MakeVisible.
Any ideas?

**Comment by SilverpointDev** [comment]
Fixed. Moved back to TSpTBXCustomTabSet.Resize

**Comment by pyscripter** [comment]
@SilverpointDev 
Thank you.  But todays changes have not been committed.

**Comment by SilverpointDev** [comment]
Forgot to commit, try again
