### ISSUE TITLE
SpTBX and VurtualImageList

### ISSUE THREAD

**Issue by alan008** [SilverpointDev/sptbxlib#106]
I'm trying to migrate to virtual image list to support multiple DPI.

I created a test app in Delphi 11.2 (per monitor v2 dpi support by default). App has one form with one SpTbxDock and one SpTbx Toolbar on it. Icons are located in ImageCollenction, toolbars references them via VirtualImageList.

My default (main) monitor is Full HD monitor with standard DPI (100% windows scale), my ext monuitor is 75" TV with 300% windows scale. When app is started all is OK (image1.png), when app window is moved to 300% scale TV , icons on toolbar become larger, but the toolbar itself grows too high, to double or triple height of icons (image2.png). When window is returned back to default monitor, all icons disappear from SpTbxToolbar. 
What am I doing wrong?
Test app included. I use SpTBX 2.5.8.

![image1](https://user-images.githubusercontent.com/2262134/233923339-0b766f3b-4284-45c2-a38d-f77fe98a4382.png)
![image2](https://user-images.githubusercontent.com/2262134/233923331-ca0dfe55-a541-4826-92a6-6885c05ad05f.png)
![image3](https://user-images.githubusercontent.com/2262134/233923322-99ab4a0f-82b3-4ea2-9ee6-2a78eeb86b66.png)

[test_app.zip](https://github.com/SilverpointDev/sptbxlib/files/11307600/test_app.zip)

**Comment by alan008** [comment]
Yes, this solves the problem with scaled size, but this doesn't solve the problem of all toolbar icons fully disappearing when the form is moved back to original monitor with 100% scale.
This is the size when window is moved from 100% to 300% monitor (all fine):
![2023-04-28_22-03-06](https://user-images.githubusercontent.com/2262134/235232276-2161ea3c-3161-4081-95e0-e10d713af72d.png)
This happens when form is moved back to initial 100% monitor:
![2023-04-28_22-03-20](https://user-images.githubusercontent.com/2262134/235232315-12045d81-fbdf-467f-9f65-1db066adbde6.png)

**Comment by alan008** [comment]
Retested with your changed version of SpGetScaledVirtualImageListSize in Delphi 10.4 Update 1. Behavior is identical to Delphi 11.1, scaled toolbar size is correct (at least seems so, identical to icons size).
But all icons still disappear from toolbar when app is moved back from scaled to initial monitor.

**Comment by alan008** [comment]
As for icons disappearing from toolbar, this is not connected any how with Virtual Image List. Button disappear from any toolbar, even when Images property of Toolbar is not set at all. 

Disappearing happens only in PerMonitor v2 DPI awareness mode. If I build test app with System DPI aware mode, then icons don't disappear from toolbar when window is moved to another monitor and then moved back.

**Comment by pyscripter** [comment]
> Replace SpGetScaledVirtualImageListSize function on TB2Common.pas with the following:

Confirm with this change it works well in Windows 11 and Delphi 11.3.

**Comment by SilverpointDev** [comment]
Can't reproduce, try the latest commit.
TB2K sources are changed, you need to re-patch it.

**Comment by alan008** [comment]
> Can't reproduce, try the latest commit. TB2K sources are changed, you need to re-patch it.

Are you sure the following conditions were met?
1) Two monitors with different Windows scaling setting (one 100% and other more than 100%).
2) App is started on one monitor dragged to another, left mouse button is released, so app stayed on second monitor, then app is dragged back to initial monitor. All icons disappear.
3) App is built with PerMonitor v2 mode. If you use System scaling mode, this bug is not reproducible.

**Comment by pyscripter** [comment]
@alan008 
> this solves the problem with scaled size, but this doesn't solve the problem of all toolbar icons fully disappearing when the form is moved back to original monitor with 100% scale.

I have tried your project with similar setup (main monitor 100%. secondary monitor 300%).  The secondary monitor was a laptop one connected wirelessly.   Delphi 11.3 and Windows 11.

I could not reproduce the dissappearance of icons.

I have tested

**Comment by pyscripter** [comment]
You can try Delphi 11 with the new community edition.

**Comment by alan008** [comment]
> You can try Delphi 11 with the new community edition.

I use Delphi 11.2 Architect on Windows 10.

**Comment by pyscripter** [comment]
Patched TB2K Source directory. (As updated today at Silverpoint).

[Source.zip](https://github.com/SilverpointDev/sptbxlib/files/11533617/Source.zip)

**Comment by alan008** [comment]
I've checked this version + latest SpTBX from github, it didn't help, icons still disappear. I'll do some debugging tomorrow to give you at least some informtation, what's going wrong.

**Comment by alan008** [comment]
I did some investigation, which might help you understand the problem.
The problem is somehow connected with TSpTbxItem.CustomHeight property.
When I add new SpTbxItem item on toolbar, in object inspector CustomHeight=-1 and CustomWidth=-1
When I run my app on default monitor (100% scale) and inspect SpTbxItem's CustomHeight at runtime it is still -1, as it was at design time.
When I move app to 300% scale monitor and inspect SpTbxItem's CustomHeight it is still -1, all OK.
When I move app back to 100% scale monitor, SpTbxItem's CustomHeight becomes 0 and Item disappears from toolbar.

If in design time I set CustomHeight to some value (more than 0), Item not disappear when app is moved to 300% scale monitor and then back.

**Comment by alan008** [comment]
This is call stack when window is moved from 300% back to 100% monitor (when CustomHeight becomes 0):

SpTBXItem.TSpTBXCustomItem.SetCustomHeight(0)
SpTBXItem.TSpTBXToolbar.ChangeScale(96,288,True)
Vcl.Controls.TControl.ScaleForPPI(96)
Vcl.Controls.TWinControl.ScaleForPPI(1699016)
Vcl.Controls.TWinControl.ScaleControlsForDpi(96)
Vcl.Controls.TWinControl.ScaleForPPI(1700044)
Vcl.Controls.TWinControl.ScaleControlsForDpi(96)
Vcl.Forms.TCustomForm.ScaleForPPIRect(96,???)
Vcl.Forms.TCustomForm.WMDpiChanged((736, (), 96, 96, (), $19F0CC, 0))
Vcl.Controls.TControl.WndProc((736, 6291552, 1700044, 0, 96, 96, (), 61644, 25, (), 0, 0, ()))
Vcl.Controls.TWinControl.WndProc((736, 6291552, 1700044, 0, 96, 96, (), 61644, 25, (), 0, 0, ()))

**Comment by alan008** [comment]
When will this change be merged into main repository? Don't see it in https://github.com/SilverpointDev/sptbxlib

**Comment by pyscripter** [comment]
Maybe Robert @SilverpointDev missed these changes or is very busy right now.

**Comment by alan008** [comment]
@pyscripter in your set of changes there is also chage about "Remove call to RightAlignItems in TSpTBXTabToolbar.Resize". Does it also address my issue or this is for some another purpose? When doing my test, I tested only TSpTBXToolbar.ChangeScale changes.

**Comment by pyscripter** [comment]
> "Remove call to RightAlignItems in TSpTBXTabToolbar.Resize"

This is related to #105.

**Comment by SilverpointDev** [comment]
Good catch! Fixed

**Comment by alan008** [comment]
> Good catch! Fixed

Sill don't see this change in the main repository. When will it be merged?

**Comment by SilverpointDev** [comment]
Forgot to commit, try again

**Comment by alan008** [comment]
Thanks. CustomWidth changes are now in main reposiotory.

In @pyscripter 's  commit https://github.com/pyscripter/SpTBXLib/commit/d4544467089a3f63510293fd4896fbf2f0a5ba80
there was another change about RightAlign items, not sure if it is merged correctly as code in main repository slightly differs.

**Comment by alan008** [comment]
Thanks everybody! You do great job!
