### ISSUE TITLE
TSpTBXCustomizeForm scaling issues

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#108]
*Issue 1*:
Procedure TSpTBXCustomizeForm.FormCreate contains the following:
```pascal
  // Setup the listboxes
  if Assigned(Customizer.Images) then begin
    lbCommands.ItemHeight := Customizer.Images.Height + PPIScale(4);
    lbShortcuts.ItemHeight := lbCommands.ItemHeight;
  end;
```
The problem is that this code is executed before the form is DPI scaled to the actual monitor DPI.   So when the form is shown, ItemHeight is DPI scaled, hence it is **scaled twice**.

To verify  move the main form of the demo to a high DPI monitor and customize the toolbars.

**Solution**:
Move the above code to procedure TSpTBXCustomizeForm.FormShow.  This gets executed after the form is scaled. 

*Issue 2*:
Also the form **ParentFont should be set to False**, otherwise the UI font is not scaled.

Note:  
In a per monitor DPI scaled app, Customizer.Images is bound to be a VirtualImageList residing in the main form.  The code assumes that Customizer form is shown  in the same monitor as the main form.  I suppose that is a reasonable assumption.

**Comment by SilverpointDev** [comment]
Fixed.
ParentFont is already set to False.
I've also fixed the ImageList scaling when using multi-monitors.

**Comment by pyscripter** [comment]
Thanks for the fix.  However is incomplete.  To reproduce the issue:

1.  Main Screen: PPI > 96 (in my case 288),  Secondary Screen: 96
2.  Move the main form to the secondary screen and invoke the customizer form.

Cause:
1.  TCustomForm .Loaded scales the form to the main screen DPI (288)
2.  TSpTBXCustomizeForm.FormCreate creates creates FInternalVirtualImage with the default size 16x16
3. When the form is shown in the secondary screen the  FInternalVirtualImage width ad hight as scaled to DPI 96 and they are too small.

Note that when you assign one virtual imagelist to another the width and height are not assigned.

Solutions:

I have changed the FormCreate as follows:
```pascal
procedure TSpTBXCustomizeForm.FormCreate(Sender: TObject);
begin
  {$IF CompilerVersion >= 33} // for Delphi Rio and up
  FInternalVirtualImage := TVirtualImageList.Create(Self);
  var Size := MulDiv(16, FCurrentPPI, Screen.DefaultPixelsPerInch);
  FInternalVirtualImage.SetSize(Size, Size);
  {$IFEND}
```
Note that Inline Variable declarations were introduced in Rio.

Another solution is to move the creation of FInternalVirtualImage to the top of TSpTBXCustomCustomizeForm.Create which is called before TCustomForm.Loaded is called, and therefore before the form is scaled.

**Comment by SilverpointDev** [comment]
Thanks, try the latest
