### ISSUE TITLE
can not put a TButton on TSpTBXTabSet

### ISSUE THREAD

**Issue by mksjgj** [SilverpointDev/sptbxlib#109]
reproduce step:
1.create a new VCL Application
2.put a TSpTBXTabSet on Form1
3.double click SpTBXTabSet1, add two TSpTBXTabItem with caption "AAA", "BBB"
4.put a TButton on TSpTBXTabSet, with caption Button1
5.run the application , you will get an error UI: "BBB" and "Button1" disappeared

[TabSetBug_.zip](https://github.com/SilverpointDev/sptbxlib/files/12777129/TabSetBug_.zip)

**Comment by SilverpointDev** [comment]
Change this on TSpTBXTabToolbar.RightAlignItems:
```pascal
    if Assigned(Spacer) then
      TSpTBXCustomItemAccess(Spacer.Item).CustomWidth := SpacerW;

    View.UpdatePositions;
```

Change it to:
```pascal
    if Assigned(Spacer) then begin
      TSpTBXCustomItemAccess(Spacer.Item).CustomWidth := SpacerW;
      View.UpdatePositions;
    end;
```

**Comment by mksjgj** [comment]
I apply your fix, but it still has error if i put a SpTBXRightAlignSpacerItem1 before the SpeedButton1









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SilverpointDev/sptbxlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月2日(星期一) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SilverpointDev/sptbxlib] can not put a TButton on TSpTBXTabSet (Issue #109)





 
Change this on TSpTBXTabToolbar.RightAlignItems:
     if Assigned(Spacer) then       TSpTBXCustomItemAccess(Spacer.Item).CustomWidth := SpacerW;     View.UpdatePositions;
 
Change it to:
     if Assigned(Spacer) then begin       TSpTBXCustomItemAccess(Spacer.Item).CustomWidth := SpacerW;       View.UpdatePositions;     end;

**Comment by SilverpointDev** [comment]
Try this:

```pascal
if Assigned(Spacer) then begin
  for I := 0 to View.ViewerCount - 1 do begin
    IV := View.Viewers[I];
    if IV.Item is TTBControlItem then
      if not IV.Show then
        Exit
      else
        if IV.BoundsRect.IsEmpty then
          Exit;
  end;

  TSpTBXCustomItemAccess(Spacer.Item).CustomWidth := SpacerW;
  View.UpdatePositions;
end;

```

**Comment by mksjgj** [comment]
It seems OK now, except a more polished fix/new version.

**Comment by SilverpointDev** [comment]
Fixed on latest commit
