### ISSUE TITLE
Customizable: TSpTBXToolbar.Visible

### ISSUE THREAD

**Issue by sergSVK** [SilverpointDev/sptbxlib#117]
Hello, All
The OnClose and OnVisibleChanged events do not fire in the settings window. Is this a design or a bug ?

Cheers

**Comment by SilverpointDev** [comment]
Can you post a simple demo that reproduces the problem?

**Comment by sergSVK** [comment]
I'm sorry. I was targeting the OnClose event. The OnVisibleChange event fires. When changing the visibility of the toolbar from the settings window.
The thread can be closed.
