### ISSUE TITLE
Do not scale ItemHeight in TSpTBXColorPickerForm

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#15]
In TSpTBXColorPickerForm.FormCreate SpTBXColorListBox1.ItemHeight is PPI scaled.  It shouldn't;, since it is automatically scaled by Delphi and it results in double scaling.

Interestingly,, in the Overview demo, SpTBXColorListBox1 and btnColorPicker do not appear scaled.   However if you create a new Delphi application and add a TSpTBXColorEdit they both appear properly scaled   It took me a while to explain the difference between the demo and a new application.   It turns out that the overview demo  is missing the 
```
Application.MainFormOnTaskBar := True;
```
statement in the dpr file.  If you add it TSpTBXColorEdit appears properly scaled!
I have added a separate issue about MainFormOnTaskBars in the demos.

**Comment by SilverpointDev** [comment]
Fixed
