### ISSUE TITLE
Add MainFormOnTaskbar in the demos

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#16]
Please add the `Application.MainFormOnTaskbar := True;` to the demos dpr files below `Application Initialize`.  It is the default since Delphi 2007.  For some strange reason this has an impact on the DPI scaling of TSpTBXColorEdit. (#15).
  
```
  Application.Initialize;
  Application.MainFormOnTaskbar := True;

```

**Comment by SilverpointDev** [comment]
Fixed
