### ISSUE TITLE
Reducing flicker

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#21]
Toolbar items flicker during form resizing.  The flicker is more pronounced with VCL styles and with forms with complex design (nested panels etc) in which re-aligning takes place during resizing.

*Reproducibility*
Use a Vcl style with the Overview demo and resize quickly.

*Potential fix*
In my fork at https://github.com/pyscripter/SpTBXLib I have implemented a solution by modifying SpTBXItem.pas.   You can use a diff utility to see the exact changes (relatively minor) but the main idea is in the SpTBXDock and SpTBXToolbar to not paint the background in the WM_ERASEBKGND handler but rather in the Paint method.   This reduces the repainting that takes place when resizing very substantially.

*Issues and side effects*
I have used this for a long time in PyScripter without any issues reported.  Resizing is smooth and flicker-free.  But a side-effect is that some SpTBXControls (SpTBXCheckBox and SpTBXRadioButton) do not paint correctly when placed on a toolbar.  The equivalent Delphi controls and other controls paint correctly and can be used instead.  I haven't looked into this deeply, but it may be related to the painting of the background of these controls.  

Do you have any idea of what causes these side effects?
Any other reasons why the introduced changes might be a bad idea?

If you would consider merging these changes I would be happy to provide a pull request.

**Comment by SilverpointDev** [comment]
Fixed
