### ISSUE TITLE
Compiling error under Delphi XE

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#22]
[DCC Error] SpTBXTabs.pas(1457): E2003 Undeclared identifier: 'Width'

**Comment by Ludens1** [comment]
Please replace in SpTBXTabs.pas line #1457 to
`B.SetSize(ARect.Right - ARect.Left, ARect.Bottom - ARect.Top;`

**Comment by SilverpointDev** [comment]
Fixed
