### ISSUE TITLE
Black controls at design-time on XE1

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#23]
![image](https://user-images.githubusercontent.com/37769776/47018971-adee3280-d15e-11e8-921f-de545e89c8e8.png)

**Comment by pyscripter** [comment]
The fix to #21 did eliminate flicker, but it has a few side-effects in the background painting of tabsheets and panels, which also affect Delphi 10.2.

**Comment by SilverpointDev** [comment]
Fixed
