### ISSUE TITLE
Decendents of TSpTBXCustomPanel do not paint correctly the background

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#26]
In a form add a TSpTBXPanel and drop a TCheckBox.   There are visual issues both at design and run time.
(Delphi 10.2)

Related to #23 

No solution yet.  Could you paint similar to TSpTBXDockablePanel using SpDrawXPDockablePanelBody?

**Comment by SilverpointDev** [comment]
Fixed
