### ISSUE TITLE
Not fixed: black SpTBXGroupBox and SpTBXRadioGroup

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#27]
![2018-10-22_232549](https://user-images.githubusercontent.com/37769776/47317341-012a1e80-d652-11e8-8db2-b3a427ac9f15.jpg)

**Comment by SilverpointDev** [comment]
Try this, change this line on SpTBXItem.TSpTBXCustomContainer.Paint:
  else
      SpFillRect(Canvas, R, Color);
To:
  else
    if Color = clNone then
      SpFillRect(Canvas, R, CurrentSkin.GetThemedSystemColor(clBtnFace))
    else
      SpFillRect(Canvas, R, Color);

**Comment by pyscripter** [comment]
I have removed and reinstalled SpTBXLib and applied the above change. 

Design time issues have been resolved.
Some runtime issues when you nest controls.

for instance:  TCheckBox inside nested SpTBXPanels.
![capture](https://user-images.githubusercontent.com/1311616/47370034-89113680-d6ed-11e8-9a70-fc3de9755e28.JPG)

Both checkboxes on the top Panel are shown correctly, though.  By the way the caption of TSpTBXPanel is not styled.


Problems also with TPanel and TSpTBXPanel inside a Tabsheet.

![capture](https://user-images.githubusercontent.com/1311616/47370290-194f7b80-d6ee-11e8-86c2-bf70e0807dcd.JPG)


TPanel is not painted correctly inside a Tabsheet and TCheckBox is not painted inside a TSpTBXPanel which is inside a Tabsheet.

**Comment by Ludens1** [comment]
> change this line on SpTBXItem.TSpTBXCustomContainer.Paint

This solve the problem partially but not completely:

![image](https://user-images.githubusercontent.com/37769776/47380934-54aa7400-d707-11e8-9f59-068b9a6a8568.png)

**Comment by SilverpointDev** [comment]
Reverted panel painting method, try the latest

**Comment by Ludens1** [comment]
[DCC Error] SpTBXControls.pas(1625): E2003 Undeclared identifier: 'tpPanelBackground'

**Comment by pyscripter** [comment]
Works great!!  Thanks very much.

**Comment by pyscripter** [comment]
I think you can close the 3 related issues.

**Comment by SilverpointDev** [comment]
Fixed
