### ISSUE TITLE
#26 not fixed

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#28]
To reproduce:
-  Start a new Vcl Application
- Drop on the main form an SpTBXPanel

Result:
![capture](https://user-images.githubusercontent.com/1311616/47317240-bc9e8300-d651-11e8-9fba-d3d8b719bbeb.JPG)

Tab controls look Ok.  However there are similar issues when dropping SpTBXPanels inside TabSheets.

**Comment by SilverpointDev** [comment]
Can't reproduce, try uninstalling the packages and rebuild the runtime and designtime packages.
