### ISSUE TITLE
SpTBXLabel, CheckBox etc. do not paint correctly inside Delphi's panels and GroupBoxes.

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#29]
To reproduce:
- Start a new Vcl Application
- Drop a TGroupBox
- Add an SpTBXLabel inside the Group box.
- Run with Vcl Styles
Design time (looks OK)
![capture](https://user-images.githubusercontent.com/1311616/47318123-e9539a00-d653-11e8-9f76-52db281eeff6.JPG)
Runtime:
![capture](https://user-images.githubusercontent.com/1311616/47318090-d214ac80-d653-11e8-8a67-af81e2b7a7a1.JPG)

This was working correctly before 697d95ce413157db77e1f33b7063500d2972efb7.

**Comment by SilverpointDev** [comment]
Can't reproduce... I used a TGroupBox and TSpTBXGroupBox and it paints as expected with different VCL Styles.
