### ISSUE TITLE
Annotate all components as suitable for Win64

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#30]
Currently you cannot add SpTBX lib components when you have selected as platform Win64.  So you need to switch to a 32 bit platform add the components and switch back to Win64 platform.  To avoid this all SpTBX components that appear at the Component Pallet need to be annotated with the following:

```
  {$IF CompilerVersion >= 23}
  [ComponentPlatformsAttribute(pidWin32 or pidWin64)]
  {$IFEND}
```

**Comment by pyscripter** [comment]
I am not sure what you mean.   If you mean that Generating 64 bit runtime compiled packages this does not help nor is necessary unless you are building applications with packages.  The IDE is a 32 bit application, but the annotation is the standard way of specifying the applicability of components.  If you look at JVCL and other component libraries, they all use such annotations.

http://docwiki.embarcadero.com/Libraries/Tokyo/en/System.Classes.ComponentPlatformsAttribute
https://stackoverflow.com/questions/27486939/is-there-simpler-way-of-saying-that-delphi-component-control-is-supported-on-all

**Comment by SilverpointDev** [comment]
That's a per component flag, you should flag the package itself.
To install and use 64 bit components you do this
1) Create/Build your Runtime package as a 32 bit package
2) Create/Build/Install your 32 bit design time package that requires the 32 bit run time
3) Add a 64 bit platform to your 32 bit run time package, compile that. The interface for the 32 bit and 64 bit are the same.

**Comment by pyscripter** [comment]
Just did that.  Had to also do it for TB2K.  Exited Delphi started again and still the components are unavailable in Win64 platform.  Maybe I am missing something.

**Comment by pyscripter** [comment]
On other components I use I never generate 64bit packages.  But with the annotations the components are available in 64bit.

**Comment by pyscripter** [comment]
VirtualTrees
```
  [ComponentPlatformsAttribute(pidWin32 or pidWin64)]
  TVirtualStringTree = class(TCustomVirtualStringTree)
```
JVCL
```
  {$IFDEF RTL230_UP}
  [ComponentPlatformsAttribute(pidWin32 or pidWin64)]
  {$ENDIF RTL230_UP}
  TJvDockVSNetStyle = class(TJvDockVIDStyle)
```

**Comment by pyscripter** [comment]
I found the documentation: http://docwiki.embarcadero.com/RADStudio/Tokyo/en/64-bit_Windows_Application_Development.  So it is either the embedded resource or the annotation.

> Making Your Components Available at Design Time and Run Time
> Following are the two ways the IDE decides whether or not a component is available for each platform. (Here "available" means appearing on the palette, and checked by the IDE. The IDE does not do any compile-time checking other than verifying the existence of component unit.) 
> Both methods described here rely on data embedded in the Win32 run-time (or design+run-time) package that implements the components. The IDE cannot load packages built for platforms other than Win32 in the IDE, so the IDE must defer to the Win32 package for information. 

- The RAD Studio build system automatically embeds an RC_DATA resource in the Win32 package binary named PLATFORMTARGETS, which is a bitmask of the pidXXX constants in System.Classes.pas and reflects the package project's targeted platforms. The IDE reads this resource when the package is loaded and uses the resource data to decide, for example, whether or not to disable the component(s) in the palette when an unsupported platform is active.
Targeting multiple platforms with a component package implies a contract between the component developer and the IDE. The IDE assumes that if a component package project targets multiple platforms and the developer distributes the Win32 run-time package to customers (and all the associated compilable and linkable files), the developer will also distribute all the necessary compilable, linkable, and run-time bits for the other targeted platforms as well.

- Individual components can use the ComponentPlatformsAttribute class attribute to override the data in PLATFORMTARGETS, using a bitmask of the same constants in the Classes unit. For example:
 type
```
   [ComponentPlatformsAttribute(pidWin32 or pidWin64)] // Only supported on Win32 and Win64
   TMyComponent = class(TComponent)
   private
     ...
   end;
```
> Use of the ComponentPlatformsAttribute attribute implies the same contract as described in the first bullet above.

**Comment by SilverpointDev** [comment]
No, the designtime remains Win32, you need to add Win64 platform on the runtime package.
And recompile/reinstall manually, this will add the new platform on the dproj file and re-create a res file with the corresponding PLATFORMTARGETS flag.

MultiInstaller doesn't use MSBuild, it doesn't use dproj files, you have to include a pre-compiled res file for the runtime package with the following rc file:
PLATFORMTARGETS RCDATA { 0x0003 }

Try the latest, it needs testing on different XE versions with MultiInstaller and manual install.

**Comment by pyscripter** [comment]
The runtime package makes no difference.  It is the design package that matters.  
PLATFORMTARGETS RCDATA { 0x0003 }
needs to get into the design package.

**Comment by SilverpointDev** [comment]
The doc is correct, the Win64 designtime package can't be loaded by the IDE because the IDE is Win32.
So it loads the Win32 runtime package and checks the flag to make the components available for Win64 development.
Please try the latest update, I only changed the runtime package files.

The res file is regenerated when needed based on the dproj file, that's why I changed it.
When using MultiInstaller which uses DCC32, the res file isn't regenerated because it doesn't use dproj, that's why I changed it.

IMHO annotations should be used when some of the components should not be available on certain platforms.
When all the existing components work for all the platforms you support and you know that all future new components on the package will also support those platforms then a general flag should be setted.
And that flag is now setted by default, no need change anything.

**Comment by pyscripter** [comment]
It works fine with manual installation.  Haven't tested with Multiinstaller.  
I am really sorry.  You were right.  It is to the runtime packages that the Win64 platform needs to be added.

I am closing the issue.  One minor point is that SpTBXLibDsgn amd SpTBXLib.dpk are saved with Unix line breaks and this causes problems to Delphi.

**Comment by SilverpointDev** [comment]
Seems that all the files are saved with Unix LF instead of CRLF... any ideas on how to change to CRLF?
Is this the right way?
https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by pyscripter** [comment]
I would suggest that you set 
git config --global core.autocrlf **false**

and make sure that that on your windows machine all files have windows line ends #13#10.  You can change the line endings with most editors.

I use TortoiseGit (very good) and it has an option on the main settings autocrlf which is unchecked by default.
