### ISSUE TITLE
The Black Controls Return

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#34]
The Black Controls are fixed for Windows Classic theme with SpTBX objects but not with common VCL:
![2018-10-27_013854](https://user-images.githubusercontent.com/37769776/47595597-d3164880-d989-11e8-8ce8-d8805caa22a4.jpg)

Unfortunately the problem persists completely with Windows 7 themes:
![2018-10-27_013652](https://user-images.githubusercontent.com/37769776/47595678-24bed300-d98a-11e8-82ef-6e24a1b7912b.jpg)

**Comment by Ludens1** [comment]
Just drop SpTBXRadioGroup on clean Form, set it's Color property to clBtnFace, and then try different Windows themes.

Windows Classic Theme:
![2018-10-30_142826](https://user-images.githubusercontent.com/37769776/47715410-c8d9a000-dc50-11e8-9e93-83f4ae001dc9.jpg)

Windows 7 Basic Theme:
![2018-10-30_142907](https://user-images.githubusercontent.com/37769776/47715539-1c4bee00-dc51-11e8-978f-7a227a4a3a4d.jpg)

Windows 7 Aero Theme:
![2018-10-30_142951](https://user-images.githubusercontent.com/37769776/47715555-28d04680-dc51-11e8-8d38-6da04cbd831d.jpg)

The last looks quite strange. 
I couldn't find a way to beat those black squares.

**Comment by SilverpointDev** [comment]
Can't reproduce, can you try the latest?
Recompile/reinstall the package

**Comment by Ludens1** [comment]
Of course, I did recompile and reinstall the library with the latest package. Tried it just now. The result is the same. I don't see a way to eliminate that black squares

**Comment by pyscripter** [comment]
I can also reproduce it.
Windows 10, Delphi 10.3
Disable Runtime themes in project options.  Showing TCheck on SpTBXPanel.

![capture](https://user-images.githubusercontent.com/1311616/47921668-d47dce80-debd-11e8-9b1a-4fa333d48f7c.JPG)

However problem disappears if I set the color of the Checkbox to clBtnFace.

**Comment by pyscripter** [comment]
@Ludens1 
You misunderstood what @SilverpointDev said.  **You do not set the color of SpTBXRadioGroup to clBtnFace but the color of the Vcl controls.**  Can you try again doing this.

**Comment by Ludens1** [comment]
> Can you try again doing this.
Yep, I tried all possible options. 
Delphi XE, Windows 7.
BTW, runtime themes setting doesn't affect the result.

**Comment by pyscripter** [comment]
So you set the Color of the TSpTBXGroupBox to clNone, The color of the TCheckBox to clBtnFace and you still get blank areas?

**Comment by pyscripter** [comment]
Just to make sure.
TSpTBXGroupBox Color := clNone
TCheckBox:  Color:=clButtonFace, ParentColor := False
and it still does not work... strange.

**Comment by Ludens1** [comment]
@pyscripter, a small correction:
SpTBXGroupBox.Color = clBtnFace (or SpTBXGroupBox.ParentColor = True)
This eliminates the black of SpTBXGroupBox. But it doesn't cure SpTBXRadioGroup:
![image](https://user-images.githubusercontent.com/37769776/47949218-3edf4f00-df50-11e8-9de8-f16ac9472ba8.png)

**Comment by SilverpointDev** [comment]
Can't reproduce on Win7/WinXP with XE, XE2, XE8, Delphi 10.2 Tokyo

**Comment by pyscripter** [comment]
I cannot reproduce it on Windows 10.  I think Aero theme is not available in Windows 10.  I thought Windows Classic theme is what you get if you do not enable runtime themes but this is application specific.  Is there a Windows classic theme for Windows 10.

**Comment by Ludens1** [comment]
@SilverpointDev 
I suppose you don't try to add some Items to SpTBXRadioGroup.
It looks normally when no Items added.

**Comment by pyscripter** [comment]
@Ludens1 I did add a couple of radio buttons.

**Comment by Ludens1** [comment]
@pyscripter 
Do you add Items under Windows 7 Basic theme?

**Comment by Ludens1** [comment]
I am able to solve the problem only with a small modification of the source code of the library.
I add `ParentColor := True;` in `constructor TSpTBXCustomRadioButton.Create(AOwner: TComponent);`

**Comment by Ludens1** [comment]
@pyscripter 
see Windows Start Menu / Control Panel /Personalization
![image](https://user-images.githubusercontent.com/37769776/47955362-3581d100-dfa8-11e8-9c36-efe8f1e1aef6.png)

**Comment by pyscripter** [comment]
No such thing in windows 10.  Nor classic.

**Comment by Ludens1** [comment]
That's Windows 7.
@SilverpointDev says he tested subj under Windows 7.

**Comment by Ludens1** [comment]
> In `constructor TSpTBXTextObject.Create(AOwner: TComponent);`
> replace `ParentColor := False;`
> with `ParentColor := True;`

Unfortunately this patch doesn't solve the problem under the Windows Aero Theme.
I don't know what else to do here.
Just dropped SpTBXRadioGroup on clear form.
![image](https://user-images.githubusercontent.com/37769776/47957025-b5fffc00-dfbf-11e8-87f4-5d6f5fa94ea8.png)

**Comment by Ludens1** [comment]
It seems to have solved the problem for all Windows themes.
Two small patches:
1
unit SpTBXItem;
constructor TSpTBXCustomContainer.Create(AOwner: TComponent);
ParentColor := False; {replace with} ParentColor := True;
2
unit SpTBXControls;
constructor TSpTBXTextObject.Create(AOwner: TComponent);
ParentColor := False; {replace with} ParentColor := True;

**Comment by SilverpointDev** [comment]
Try the latest

**Comment by Ludens1** [comment]
Problem solved! I'm absolutely happy. Thank you very much!
