### ISSUE TITLE
Regression on SpTBXTabControl 

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#35]
I am using the SpTBXTabControl in PyScripter (https://github.com/pyscripter/pyscripter/) and each tab contains Editor instances (SynEdit) with alClient alignment i.e. covering the whole Tabsheet.

Before commit 697d95ce413157db77e1f33b7063500d2972efb7 switching tabs was smooth, fast and without flicker, but now when I switch tabs the whole background is repainted in a visible and annoying way and it is much slower.  I had to revert to my fork (https://github.com/pyscripter/sptbxlib/) which is synched to your repository before that commit.   I guess this has something to do with the removal of GetFullRepaint.   If I am not wrong GetFullRepaint returned false when a tab was visible and no background painting was taking place.

By the way the SpTBXTabControl and the SpTBXStatusBar are by a long margin the best of their kind!

**Comment by SilverpointDev** [comment]
Can you try the latest?

**Comment by pyscripter** [comment]
I did some further tests on this.
The unresponsiveness during resizing is solely due to the Tabsheets.  If I have no Tabsheet in the tab control, resizing is smooth as with ompiling with my form. As soon as I add even one Tabsheet resizing becomes unresponsive.  Is this related to the lack of GetFullRepaint?

**Comment by SilverpointDev** [comment]
Can you try the latest?

**Comment by pyscripter** [comment]
Still resizing unresponsive once you have at least one Tabsheet active.  OK without any tabsheets.

**Comment by pyscripter** [comment]
I probably  should mention that my SpTBXTabControl is inside an SpTBXPanel with color <> clNone.

**Comment by pyscripter** [comment]
To give you an idea, this is what I have trouble resizing.
![capture](https://user-images.githubusercontent.com/1311616/47955534-521b0a80-dfa2-11e8-8d58-d8f710ef9dd8.JPG)

**Comment by pyscripter** [comment]
I have reproduced the issue in a tiny project (attached).   The problem is caused by
//  TStyleManager.Engine.RegisterStyleHook(TCustomSynEdit, TScrollingStyleHook);
This style hook styles the scrollbars of the SynEdit control.   Without the Style hook the program runs fine and resizing is smooth.  Adding the style hook breaks the project.
Now the same project used to work fine, with the style hook.  You can confirm that by switching to the state of the repository before commit  697d95c.  

[Project8.zip](https://github.com/SilverpointDev/sptbxlib/files/2545251/Project8.zip)

**Comment by SilverpointDev** [comment]
Try the latest, removed WS_EX_COMPOSITED window style.
Using WS_EX_COMPOSITED on TSpTBXPanel causes incorrect painting when child controls use TScrollingStyleHook.
To reproduce:
- Drop a TMemo inside a TSpTBXPanel
- Change Memo.ScrollBars to ssVertical
- Run and try to resize using a VCL Style.
Seems to be a VCL Styles bug, when the parent control has WS_EX_COMPOSITED setted, TScrollingStyleHook.WndProc gets called non stop, even when the window is not visible.
TScrollingStyleHook.WndProc calls TScrollingStyleHook.PaintNC which constantly shows and repaints the scrollbars.

**Comment by pyscripter** [comment]
Will try tonight.
Thanks.

**Comment by pyscripter** [comment]
Resizing has improved and now is acceptable.  However there are issues with the invalidation of the SpTBXTabControl.
When I create a new Tab neither the tab bar nor tabsheet area get updated.  I have to cause of full repaint for the new sheet to appear by say moving another form on top of it.
Also even when I close all tabs there invalidation issues.   For example when I resize an empty tab control (no sheets) I get the artefacts shown in the picture below:

![capture](https://user-images.githubusercontent.com/1311616/48232455-5720f500-e3ba-11e8-8c3d-768c5cf84b79.JPG)

**Comment by pyscripter** [comment]
I would like to add that although the resizing speed is acceptable, the version in my fork i.e your reposity before commit 697d95c provides a much faster and nicer resizing experience.

**Comment by SilverpointDev** [comment]
Try the latest.

Before [697d95c](https://github.com/SilverpointDev/sptbxlib/commit/697d95ce413157db77e1f33b7063500d2972efb7) there were many problems, to reproduce:
- Drop a TPanel, TCheckBox and TSpTBXCheckbox inside a TSpTBXPanel
- Set TSpTBXPanel.Align = alClient
- Set TSpTBXPanel.TBXStyleBackground = True
- Run, set the Skin to Athen
- Resize the form to a minimum and slowly resize

Artifacts on VCL controls and incorrect background painting on SpTBXCheckbox.
The same happens when VCL Styles are used.
More problems with nested Panels, and TabControls....


After [697d95c](https://github.com/SilverpointDev/sptbxlib/commit/697d95ce413157db77e1f33b7063500d2972efb7) there were many problems, to reproduce:
- Drop a TPanel, TCheckBox and TSpTBXCheckbox inside a TSpTBXPanel
- Set TSpTBXPanel.Align = alClient
- Set TSpTBXPanel.TBXStyleBackground = True
- Run, set the Skin to Athen
- Resize the form to a minimum and slowly resize

Artifacts on VCL Panel.
When you use a VCL Style TCheckbox is white and artifacts are shown on TPanel.
More problems with nested Panels, and TabControls....

**Comment by SilverpointDev** [comment]
Calling Add repaints the TabSheet and Tab items.
Can you post a simple project that reproduces the problem?

**Comment by pyscripter** [comment]
The following pattern used to work but now it doesn't.  The Tabcontrol does not get updated.  Easy to replicate.
TabControl.Toolbar.BeginUpdate;
try
  TabControl.Add('tab');
  // do something
finally
  TabControl.Toolbar.EndUpdate;
end;

**Comment by pyscripter** [comment]
By the way this https://stackoverflow.com/questions/18734761/ws-ex-composited-cause-unexpected-wm-paint may explain the earlier issue.

**Comment by pyscripter** [comment]
Great improvement in resizing!!  Now it acceptable and comparable to what it was before 697d95c.

The removal of  `TSpTBXTabToolbarView.BeginUpdate` though causes some flicker when you create tabs.

The following works well for me.
```
procedure TSpTBXTabToolbarView.BeginUpdate;
var
  T: TSpTBXTabToolbar;
begin
  if (FUpdating = 0) and (Owner is TSpTBXTabToolbar) then begin
    T := TSpTBXTabToolbar(Owner);
    if Assigned(T.FOwnerTabControl) then
      SendMessage(T.FOwnerTabControl.Handle, WM_SETREDRAW, 0, 0);
  end;
  inherited;
end;

procedure TSpTBXTabToolbarView.EndUpdate;
var
  T: TSpTBXTabToolbar;
begin
  inherited;
  if (FUpdating = 0) and (Owner is TSpTBXTabToolbar) then begin
    T := TSpTBXTabToolbar(Owner);
    if Assigned(T.FOwnerTabControl) then begin
      SendMessage(T.FOwnerTabControl.Handle, WM_SETREDRAW, 1, 0);
      //T.InvalidateNC; not needed I think
      T.FOwnerTabControl.InvalidateBackground(True);
    end;
  end;
end;
```
It is a good idea to add the updated patch to the repo.

**Comment by SilverpointDev** [comment]
Restored BeginUpdate/EndUpdate
