### ISSUE TITLE
Problem with resizing forms with SpTBXStatusBar

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#36]
As you can see in the picture below, during and after resizing a form with an SpTBXStatus bar, the status bar is not repainted correctly.  You need to force a repaint by say moving the mouse on top of it for the control to repaint properly again.

![capture](https://user-images.githubusercontent.com/1311616/47888808-250a1300-de4f-11e8-841d-5751c33fbe4c.JPG)

**Comment by SilverpointDev** [comment]
Can you reproduce it on a clean new project?

**Comment by pyscripter** [comment]
Yes this solves the problem.

**Comment by pyscripter** [comment]
Please close the issue once you commit the above.
