### ISSUE TITLE
Strange view of TSpTBXStatusBar

### ISSUE THREAD

**Issue by Makhaon** [SilverpointDev/sptbxlib#38]
In Delphi XE6 new version of TSpTBXStatusBar looks strange in non Windows theme (Carbon). You can see on the screenshot
![default](https://user-images.githubusercontent.com/35131832/48700729-cccc6280-ebfd-11e8-8e51-4692967ed7c6.PNG)

**Comment by Ludens1** [comment]
Not only XE6. 
XE and 10.2 too.

**Comment by SilverpointDev** [comment]
Change this line of TB2Item.pas in TTBView.DrawItem and try again:
FWindow.Perform(WM_ERASEBKGND, WPARAM(BmpDC), 0);
To
FWindow.Perform(WM_ERASEBKGND, WPARAM(BmpDC), LPARAM(BmpDC));

Or try the latest, and re-apply TB2K patch

**Comment by Makhaon** [comment]
>FWindow.Perform(WM_ERASEBKGND, WPARAM(BmpDC), LPARAM(BmpDC));
I have already applied this change

**Comment by SilverpointDev** [comment]
Can you post a simple demo project that reproduces the problem?

**Comment by Makhaon** [comment]
I found issue here, I redownloaded the lib, tb2000 and seem to all works fine. Thank you very much for great library and sorry to bother you. Ticket can be closed.
