### ISSUE TITLE
Components on TTBControlItem doesn't support shrink mode

### ISSUE THREAD

**Issue by Makhaon** [SilverpointDev/sptbxlib#47]
To reproduse just put any component into control container (TTBControlItem) on the toolbar. And make form slimmer.

**Comment by SilverpointDev** [comment]
When ShrinkMode is tbsmWrap the TTBControlItem is correctly wrapped.
When ShrinkMode is tbsmChevron the TTBControlItem doesn't appear on the chevron popup, this is a TB2K limitation, only toolbar items can be placed on popups.
