### ISSUE TITLE
SpTBXEditItem1.StartEditing does not work properly

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#49]
1. Add SpTBXEditItem1 into SpTBXToolbar1.
2. Put any text into SpTBXEditItem1.Text property.
3. Call SpTBXEditItem1.StartEditing(SpTBXToolbar1.View) using a hotkey (not by mouse click).
4. Press Enter.
5. Call SpTBXEditItem1.StartEditing again using a hotkey.
6. Get surprised.

**Comment by Ludens1** [comment]
[49.zip](https://github.com/SilverpointDev/sptbxlib/files/3709335/49.zip)

**Comment by Ludens1** [comment]
![image](https://user-images.githubusercontent.com/37769776/66519033-24620e00-eaef-11e9-87d7-7aa0942a338c.png)

**Comment by Ludens1** [comment]
If it matters: XE

**Comment by SilverpointDev** [comment]
Fixed
