### ISSUE TITLE
SpTBXStatusBar get black after refresh

### ISSUE THREAD

**Issue by ats3788** [SilverpointDev/sptbxlib#50]
On the Test Program Overview when I push the Button subLang2
the whole Status bar is getting black
when I move the mouse over the Button  subLang2
the Button is changing back to grey. I  changed the ParentColor like
in The Black Controls Return
#34 by Ludens1 was closed on 8 Nov 2018
described, with no success.
With an older version I had never had this Problem.

**Comment by SilverpointDev** [comment]
TB2K patch was changed on the last commit, you have to reinstall TB2K and SpTBXLib, and re-apply the TB2K patch.

**Comment by ats3788** [comment]
I Reinstalled TB2K and SpTBXLib and I get this when I apply ehe patch


D:\__Dokus\Comps.XE7\SpTBXLib.2.5.5\TB2K Patch>tb2kpatch.bat

D:\__Dokus\Comps.XE7\SpTBXLib.2.5.5\TB2K Patch>p_atch.exe -p0 --batch --input=tb2kdiff.txt
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Acc.pas Sat Apr 19 00:31:00 2008
|+++ TB2Acc.pas Mon Sep 03 09:30:03 2018
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 15
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Common.pas      Wed Sep 17 14:46:30 2008
|+++ TB2Common.pas      Thu Nov 15 11:15:20 2018
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
can't find file to patch at input line 65
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Dock.pas        Wed Sep 17 15:12:26 2008
|+++ TB2Dock.pas        Fri Dec 28 13:19:15 2018
--------------------------
No file to patch.  Skipping patch.
20 out of 20 hunks ignored
can't find file to patch at input line 357
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2DsgnItemEditor.pas      Thu Sep 25 13:49:32 2008
|+++ TB2DsgnItemEditor.pas      Mon Sep 03 09:30:04 2018
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 369
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2ExtItems.pas    Thu Apr 10 16:51:12 2008
|+++ TB2ExtItems.pas    Mon Sep 03 09:30:04 2018
--------------------------
No file to patch.  Skipping patch.
13 out of 13 hunks ignored
can't find file to patch at input line 542
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Item.pas        Fri Sep 19 11:35:48 2008
|+++ TB2Item.pas        Thu Nov 15 11:15:32 2018
--------------------------
No file to patch.  Skipping patch.
32 out of 32 hunks ignored
can't find file to patch at input line 1061
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Reg.pas Thu Sep 18 14:08:40 2008
|+++ TB2Reg.pas Mon Sep 03 09:30:04 2018
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 1080
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Toolbar.pas     Mon Jun 23 13:05:48 2008
|+++ TB2Toolbar.pas     Mon Sep 03 09:30:04 2018
--------------------------
No file to patch.  Skipping patch.
5 out of 5 hunks ignored
can't find file to patch at input line 1152
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2ToolWindow.pas  Wed Jan 05 20:56:50 2005
|+++ TB2ToolWindow.pas  Mon Sep 03 09:30:04 2018
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 1177
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- TB2Ver.inc Sat Sep 13 16:06:46 2008
|+++ TB2Ver.inc Mon Nov 26 10:45:10 2018
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

**Comment by SilverpointDev** [comment]
To manually install the patch you have to move all 3 files on TB2K Patch folder to the source folder of TB2K and run tb2kpatch.bat.
Or just use [MultiInstaller](http://www.silverpointdevelopment.com/multiinstaller/index.htm)
