### ISSUE TITLE
Sorry for stupid question, but i have that type of error in my BDS 2006:

### ISSUE THREAD

**Issue by MadRatSRP** [SilverpointDev/sptbxlib#52]
[Pascal Error] sitCompilerMessagesPanel.pas(68): E2003 Undeclared identifier: 'SkinType'

It shows up when i try to call assignment like this one FListBox.SkinType := sknWindows;
and FListBox is TSptbListBox type

I'm using version 2.4.8. Do i need older version or what?

**Comment by MadRatSRP** [comment]
I see, i need version 2.4.7. Do you still have it?

**Comment by SilverpointDev** [comment]
You can download 2.4.8 from [here](http://www.silverpointdevelopment.com/sptbxlib/downloads.htm)
