### ISSUE TITLE
TSpTBXFloatingWindowParent caption not painting correctly under Windows skin.

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#55]
Run the Overview demo and make the Toolbars floating.  Under Windows 10 I a seeing something like this:
![image](https://user-images.githubusercontent.com/1311616/75639392-36c51b80-5c39-11ea-90ef-81ce6af6a613.png)
Please note that TB2K has a similar issue, so the issue is inherited from TB2K's TTBXFloatingWindowParent .

**Comment by pyscripter** [comment]
This is due to the use of WS_THICKFRAME.  In Windows 10 a 6px frame is displayed at the top.   It is best to avoid using WS_THICKFRAME.

This is fixed in the DPI awareness patch.

**Comment by SilverpointDev** [comment]
Fixed
