### ISSUE TITLE
Radiobuttons has wrong size on the non Windows theme on the latest sources

### ISSUE THREAD

**Issue by Makhaon** [SilverpointDev/sptbxlib#57]
Hi, I have found an issue.
Just run Overview with any non-Windows delphi theme. For example I have attached Auric theme.
My soft environment: Delphi XE6 Windows 10 125% Font size (monitor DPI).
Radiobuttons are too small.
Please, fix th issue!
![image](https://user-images.githubusercontent.com/35131832/99245656-fe8c5a00-2814-11eb-9e62-17dd4086ab4d.png)

**Comment by pyscripter** [comment]
High-DPI is supported only on Tokyo or later.  DPI aware Vcl Styles  was introduced in Delphi 10.4.
You could use though the Vcl.Styles.DPIAware unit from the Vcl.Styles project (on Github).

My suggestion would be to mark your application as DPI unaware using a manifest file.

**Comment by Makhaon** [comment]
Connection of the Vcl.Styles.DPIAware unfortunatelly doesn't helps. Nothing has changed.

**Comment by Makhaon** [comment]
TCustomStyle.DoGetElementSize returns zero values for Details.Part = 2 (THEME_BP_RADIOBUTTON)

**Comment by SilverpointDev** [comment]
Fixed
