### ISSUE TITLE
Cosmetic menu draw issue in high DPI

### ISSUE THREAD

**Issue by AlbertWiersch** [SilverpointDev/sptbxlib#58]
I noticed this issue when testing my app for high DPI support... I think it might finally happen thanks to component improvements for high DPI in SpTBX and others!!!

It looks like the line needs to be drawn further to the left. Component is a TSpTBXSubmenuItem with DropdownCombo=true.

![MenuDrawBug](https://user-images.githubusercontent.com/7662186/101208219-6f19e000-3637-11eb-900f-84b9edc1c2c2.png)

**Comment by SilverpointDev** [comment]
Fixed in latest
