### ISSUE TITLE
Cosmetic issue with TSpTBXToolbars when moving to lower DPI

### ISSUE THREAD

**Issue by AlbertWiersch** [SilverpointDev/sptbxlib#59]
I noticed that there is excess space between to TSpTBXToolbars when my app is moved to a lower DPI monitor. It seems the width of the toolbars is not being adjusted downward for the new lower DPI? Or perhaps the position of the 2nd toolbar is not being adjusted for the new lower DPI?

See screenshots. First is high DPI and second is after moving the form to a lower DPI monitor.

![2020-12-07_16-39-49](https://user-images.githubusercontent.com/7662186/101414689-2fa7f980-38ac-11eb-831d-0e5fb035737a.png)

![2020-12-07_16-41-00](https://user-images.githubusercontent.com/7662186/101414783-5bc37a80-38ac-11eb-80f3-318672b96e0c.png)

**Comment by SilverpointDev** [comment]
Fixed in latest
