### ISSUE TITLE
Can't build latest sources

### ISSUE THREAD

**Issue by AlbertWiersch** [SilverpointDev/sptbxlib#64]
I patched TB2K with the new patch.

I am trying to build the latest sources.

I am getting these errors for SpTBXLib.bpl and SpTBXLibDsgn.bpl:
[dcc32 Error] SpTBXPageScroller.pas(260): E2250 There is no overloaded version of 'PaintThemedElementBackground' that can be called with these arguments
[dcc32 Error] SpTBXPageScroller.pas(265): E2035 Not enough actual parameters
[dcc32 Fatal Error] SpTBXLib.dpk(52): F2063 Could not compile used unit 'SpTBXPageScroller.pas'

**Comment by pyscripter** [comment]
I suppose you are using Delphi 10.3 ...

**Comment by AlbertWiersch** [comment]
No, I'm using 10.4.1... unless I somehow loaded up 10.3 by accident because it's on my system as well. Does it build for you in 10.4.1? Am I doing something wrong? I wanted to re-build with the recent DPI fixes.

**Comment by SilverpointDev** [comment]
Fixed in latest commit
