### ISSUE TITLE
Strange behaviour with "anchored" TTBControlItem

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#67]
Steps to reproduce:
- Open the Overview demo in a high-dpi monitor (not sure this is essential)
- Select the SPTBXComboBox1
-  Try to reduce the width 

Result:  The width grows

Also sometimes you save the form with a given width of SPTBXComboBox1, close the project, reopen it and the width is different.

Finally if you float the toolbar containing SPTBXComboBox1 (with the "Address" label), then reduce the floating window width so that the Go button wraps into a new row and then dock the floating toolar back SPTBXComboBox1 becomes invisible (zero width).

The problem occurs in the following lines of procedure TSpTBXToolbar.AnchorItems:

```pascal
          if FAnchoredControlItems[J].Dock = CurrentDock then begin
            FAnchoredControlItems[J].Width := FAnchoredControlItems[J].Width + UpdatedDelta;
            CI.Control.Width := FAnchoredControlItems[J].Width + (Size.X - FAnchoredControlItems[J].ParentWidth);
          end;
```

IsAnchoredControlItem considers a control Anchored if that Alignment is alClient or akRight is in Anchors.  So a workaround is to make sure none of the above is true.   If the the TTBControlItem is not considered anchored none of the issues discussed above occurs.

By the way, what is anchored property meant to achieve?

**Comment by SilverpointDev** [comment]
I think it's fixed, need more testing, try the latest.

When Anchored is set to True it stretches the item when the dock is resized.
When a control on a toolbar has akRight in Anchors the toolbar stretches the control when the dock is resized.

**Comment by pyscripter** [comment]
It works much better now.

**Comment by pyscripter** [comment]
In  TSpTBXToolbar.DoItemNotification

``` pascal
   case Action of
      tbicInserted:
        RightAlignItems;
      tbicDeleting:
        RightAlignItems;
      tbicInvalidateAndResize:
        RightAlignItems;
    end;
```

can be written more concisely...
