### ISSUE TITLE
Floating toolbar window border painted incorrectly with Vcl Styles

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#69]
![image](https://user-images.githubusercontent.com/1311616/103393346-df2e5f80-4b2a-11eb-9296-8fc44c21e755.png)

You can see the white space at the bottom left border and the bottom border is not drawn.  Please note that this painted correctly with my PR, but I am not sure yet as to which change makes for the difference.

**Comment by pyscripter** [comment]
Here is the fix:

a)  In SpTBXItem.pas SpDrawXPTitleBarBody, there are four calls to PaintThemedElementBackground.  In all calls replace the DPI argument with 0.  Borders do no scale.

b)  In SpTBXItem.pas there are three GetFloatingBorderSize methods.  In all three for SkinType = sknDelphiStyle  add 2 to Result.X and Result.Y.  I am not sure why this is needed.

**Comment by SilverpointDev** [comment]
Fixed on latest.
