### ISSUE TITLE
Impossible to compile with Delphi XE

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#7]

**Comment by Ludens1** [comment]
**[DCC Fatal Error] SpTBXSkins.pas(67): F1026 File not found: 'System.Generics.Collections.dcu'**

I replace 'System.Generics.Collections' with 'Generics.Collections' in uses clause of SpTBXSkins.pas.
Then I get

**Error Reading Form 'SpTBXColorPickerForm'
Class TSpTBXTabControl not found. 

Error creating form: Class TSpTBXTabControl not found

[DCC Fatal Error] SpTBXColorPickerForm.pas(48): F1026 File not found: 'System.ImageList.dcu'** 

After removing 'System.ImageList' from SpTBXColorPickerForm.pas I get success compiling but I'm not sure that this is a proper solution.

**Comment by pyscripter** [comment]
It is.

**Comment by Ludens1** [comment]
Thank you for good news!
It would be great if you add something with {$IF CompilerVersion = 22} to SpTBXSkins.pas and SpTBXColorPickerForm.pas files.

**Comment by SilverpointDev** [comment]
Fixed
