### ISSUE TITLE
Font Preview not showing with certain Vcl Styles

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#70]
If you try the Overview demo with the Windows10Blue style the font preview is not showing.  Probably wrong colors chosen.

**Comment by pyscripter** [comment]
Adding to TSpTBXFontComboBoxPreview.Create the following appears to fix the issue:

`  FPreviewPanel.StyleElements := FPreviewPanel.StyleElements - [seFont];
`

**Comment by SilverpointDev** [comment]
Fixed on latest.
