### ISSUE TITLE
Dockable windows height not scaled

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#71]
If you try the Overview demo and move the Window in a monitor with different DPI than the original one, the height of the dockabale windows on the left and right is not scaled.

My PR make an effort to scale the height of vertically docked windows and the width of the horizontally docked ones so that the form looks the same.

**Comment by pyscripter** [comment]
By the way I am done with my testing for now and the rest appears to work well.

**Comment by SilverpointDev** [comment]
Try the latest, more testing needed.
In order for this to work properly there's a change you need to make in TB2K:

function TTBDock.DefaultScalingFlags: TScalingFlags;
begin
  // Result := [];
  // Reverted to old behavior, it was causing incorrect aligning when changing
  // DPI, to reproduce right align a dock with a toolbar, and right align
  // a splitter, the splitter should be on the left side of the toolbar,
  // changing DPI causes incorrect splitter alignment.
  Result := inherited;
end;
