### ISSUE TITLE
SpGetTextSize returns unexpectedly zero

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#72]
Steps to reproduce:
1.  Add   'Assert(Result.cx <> 0);'  as the last statement of SpGetTextSize 
2.  Compile the Overview demo in **64bits** and run

I get the following.
![image](https://user-images.githubusercontent.com/1311616/103538491-f52b7f80-4e9e-11eb-80cf-0afab744a1cf.png)

Fix: 
Replace in SpTBXEditors.pas in SpCalcMaxDropDownWidth
`  Sz := SpGetTextSize(C.Handle, Combo.Items[I], False);
`
with
`Sz := C.TextExtent(Combo.Items[I]);
`
Notes:
-  It does not occur in 32 bits.
- The error occurs while loading the form
- It is hard to see why TextExtend works and SpGetTextSize does not.  They end up calling the same routine, but the handle is different.

**Comment by SilverpointDev** [comment]
Fixed on latest.
