### ISSUE TITLE
Cannot compile under XE, tb2k repatched

### ISSUE THREAD

**Issue by Ludens1** [SilverpointDev/sptbxlib#73]
2.5.7 refuses to compile under XE with repatched tb2k.

[DCC Fatal Error] SpTBXLib.dpk(35): E2202 Required package 'vclwinx' not found

**Comment by Ludens1** [comment]
I tried to completely repatch and recompile, the result is:

[DCC Error] TB2Item.pas(2776): E2003 Undeclared identifier: 'TTBFloatingWindowParent'

(Delphi XE, Windows 7)

**Comment by Ludens1** [comment]
Reverted to 2.5.6 :(

**Comment by SilverpointDev** [comment]
Fixed, try the latest

**Comment by Ludens1** [comment]
Unfortunately the problem with compiling under XE persisted:
![image](https://user-images.githubusercontent.com/37769776/105420362-4aaead00-5c51-11eb-8e3d-f7a112d094b3.png)
[DCC Error] TB2Item.pas(2776): E2003 Undeclared identifier: 'TTBFloatingWindowParent'

(tb2k 2.2.2 was repatched again)
