### ISSUE TITLE
Controls draw onto the border of dockable windows

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#77]
This is a minor visual issue.

Run the Overview demo
Look at the image below
![image](https://user-images.githubusercontent.com/1311616/106217317-a80ca600-61dd-11eb-9827-bb0f47281ef6.png)

The issue is present with skins and Delphi styles.

**Comment by SilverpointDev** [comment]
This happens because the container (TSpTBXTabControl) doesn't have a NC area. 
It mimics the behavior of VCL containers.
