### ISSUE TITLE
Add filter options to TSpTBXFontComboBox

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#78]
In https://github.com/pyscripter/SpTBXLib/blob/master/Source/SpTBXExtEditors.pas I have added a FilterOptions property to TSpTBXFontComboBox.

```pascal
  TSpTBXFontFilterOption = (ffScalableOnly, ffFixedPitchOnly);
  TSpTBXFontFilterOptions = set of TSpTBXFontFilterOption;
```
It would be nice if you could add the above to your repo.

**Comment by SilverpointDev** [comment]
Ok, I added FilterFontPitch and FilterFontType properties to filter the font list.

**Comment by pyscripter** [comment]
Thanks!
