### ISSUE TITLE
Are older branches/zip files available?

### ISSUE THREAD

**Issue by mobruk** [SilverpointDev/sptbxlib#79]
I'm attempting to compile and install in XE7. However, the latest code seems to be written for Delphi XE10 - the high resolution properties will not compile in XE7:

```
unit SpTBXCustomizer;
procedure SpLoadFormState(Form: TCustomForm; OptionsList: TStrings);

   ...
        MulDiv(R.Left, Form.CurrentPPI, DPI),
   ...

```
```
E2003 Undeclared Identifier: 'CurrentPPI'
```

I'm actually upgrading from and even older version of Delphi to XE7, and then will upgrade to XE10.4 later this year. We want to stop at XE7 and deal with any new issues prior to updating to XE10.4.

**Comment by SilverpointDev** [comment]
Fixed.
For older zip files see:
https://github.com/SilverpointDev/sptbxlib/releases
