### ISSUE TITLE
Spin edit buttons do not DPI scale.

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#8]
Add a spin edit item to the toolbar of the Overview demo and run in a high-DPI monitor.  You will see that the spin button is not scaled.

Fix:

In SpTBXEditors.pas change
```
const
  DefaultSpinButtonSize = 14;
```

to 
`
function DefaultSpinButtonSize: Integer; begin Result := SpDPIScale(14); end;
`

**Comment by SilverpointDev** [comment]
Fixed
