### ISSUE TITLE
In the overview demo the image list items are not scaled at application start.

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#80]
Just run the demo on a high DPI monitor and observe the size of the icons.

Explanation:  The ImageList is creaed in the FormCreate event handler.  This happens after loading the form and the initial scaling of the form happens in the Loaded method.

Solution:  Move the image list creation to a new Loaded method:

```
procedure TForm1.Loaded;
begin
  IL := TSpTBXImageList.Create(Self);
  inherited;
end;
```

**Comment by SilverpointDev** [comment]
Fixed in latest commit
