### ISSUE TITLE
Theming for TTBDock's BoundLines property.

### ISSUE THREAD

**Issue by MShark67** [SilverpointDev/sptbxlib#83]
When using the BoundLines property combined with Vcl.Styles they are drawn in non-styled colors.  To fix this I use:

      if StyleServices.Available then
      begin
        HighlightPen := CreatePen(PS_SOLID, 1, StyleServices(Self).GetSystemColor(clBtnHighlight));
        ShadowPen := CreatePen(PS_SOLID, 1, StyleServices(Self).GetSystemColor(clBtnShadow));
      end
      else
      begin
        // The original code
        HighlightPen := CreatePen(PS_SOLID, 1, GetSysColor(COLOR_BTNHIGHLIGHT));
        ShadowPen := CreatePen(PS_SOLID, 1, GetSysColor(COLOR_BTNSHADOW));
      end;

in the TTBDock.DrawNCArea method.  I'm sure this is not the correct way to handle it, but just in case this helps.

**Comment by SilverpointDev** [comment]
Fixed
