### ISSUE TITLE
Add ImageName property to TBItem

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#85]
Since Delphi Rio ImageLists, Actions and Controls wilh images support the ImageName property.

Please provide support for ImageName to the TBItem.

**Comment by SilverpointDev** [comment]
On the to-do list.
In order to implement this I'll have to make separate packages for different Delphi versions.

**Comment by SilverpointDev** [comment]
ImageName was introduced on Sydney

**Comment by SilverpointDev** [comment]
ImageName added to TTBCustomItem and SpTBXLib controls. I've also added the corresponding property editor.
