### ISSUE TITLE
Wrong 64x code

### ISSUE THREAD

**Issue by Makhaon** [SilverpointDev/sptbxlib#91]
procedure TSpTBXPopupWindowView.SetIsToolbar(const Value: Boolean);

PBoolean(Integer(Self) + (Integer(GetPropInfo(TSpTBXPopupWindowView, 'IsToolbar').GetProc)

pointes has 64x size, not 32x in the integer.

**Comment by SilverpointDev** [comment]
Change the line to:
PBoolean(@(Self.IsToolbar))^ := Value;

**Comment by SilverpointDev** [comment]
Fixed
