### ISSUE TITLE
ver 2.5.8: Tool buttons with DrowdownArrow and empty caption look weird: dropdown arrow is now too close to image (partial overlap)

### ISSUE THREAD

**Issue by alan008** [SilverpointDev/sptbxlib#93]
![2021-07-06_11-19-54](https://user-images.githubusercontent.com/2262134/124734505-db3a2a80-df1d-11eb-8165-5b3e52324e41.png)
[SpTBX_Test.zip](https://github.com/SilverpointDev/sptbxlib/files/6775996/SpTBX_Test.zip)

See screenshot and example project

**Comment by pyscripter** [comment]
I think this is fixed in Version Control.

**Comment by alan008** [comment]
Thanks, migrated to master (trunk), as no version after 2.5.8 was released. No error now, painted OK
