### ISSUE TITLE
Ugly disabled icon drawing with normal TImageList

### ISSUE THREAD

**Issue by benok** [SilverpointDev/sptbxlib#94]
Hi, 
Thank you for developing SpTBXLib! I really appreciate your work. :-)

I'm planning to support DPI awareness of my app built with SpTBXLib.

I updated SpTBXLib from an old version to latest git master branch version, 
I found my app's disabled icon looks ugly (like normal TToolbar).

I found new TVirtualImageList drawing routine fallbacks to normal TImageList.
https://github.com/SilverpointDev/sptbxlib/blob/master/TB2K%20Patch/tb2kdiff.txt#L270

I think it should be drawn as before.

**Comment by SilverpointDev** [comment]
Fixed.
Improved the painting on older versions of Delphi.
Improved the painting when the ImageList is not a VirtualImageList.
