### ISSUE TITLE
Disabled icons drawing

### ISSUE THREAD

**Issue by alan008** [SilverpointDev/sptbxlib#96]
After you migrated to TImageList, disabled icons drawing changed to worse.
We are using Delphi 10.4.1

Picture 1 - how disabled icons were drawn before you migrated to TImageList
Picture 2 - how disabled icons were drawn with your trunk version before July 29 commit
Picture 3 - how disabled icons are drawn now , after your July 29 commit

Could you please change disabled icons drawing to grayscale/monochrome as shown in Picture 1. PLEASE !!! We are begging you! Disabled Icons should not be full-colored, it confuses users (they don't distinguish enabled and disabled icon well).

![Picture 1](https://user-images.githubusercontent.com/2262134/127660340-ae9017c8-5f6b-4b13-8d6e-47d193aea928.png)
![Picture 2](https://user-images.githubusercontent.com/2262134/127660338-8fcd485d-8a9e-4a67-86bd-8b5924f8c107.png)
![Picture 3](https://user-images.githubusercontent.com/2262134/127660335-026829ee-0534-49fb-8f3a-76410108dd82.png)

**Comment by SilverpointDev** [comment]
You are right, disabled icons should not be colored.
Reverted, fixed on latest.
