### ISSUE TITLE
Delphi 11 designer shows component icons without transparency.

### ISSUE THREAD

**Issue by pyscripter** [SilverpointDev/sptbxlib#99]
See example below:

![image](https://user-images.githubusercontent.com/1311616/137565790-549acdc7-ac4f-4428-8b63-6eda1f09230c.png)

Maybe is time to switch to 32bit bitmaps with alpha transparency.

**Comment by SilverpointDev** [comment]
Seems like a Delphi 11 bug.
I'm guessing the IDE is using a TVirtualImageList but it doesn't process the lower left pixel color when the bitmap isn't 32bit.
If we start using 32bit bitmaps I will have to create different packages for different Delphi versions.
Or add PNGs, older versions will still use the bitmaps, newer versions (Tokyo and up) will use PNGs.

**Comment by SilverpointDev** [comment]
Further testing shows the IDE is using only 2 sizes of bitmaps.

I've changed the dcr with different colored bitmaps for 3 different sizes.
Cyan background for 16x16
Red background for 24x24
Blue background for 32x32

Steps to reproduce
1) Tools - Options - User Interface - Palette - Button Size
2) Change the size to Small: the IDE uses 16x16 bmp
3) Change the size to Medium: the IDE uses 32x32 bmp, scales it down, it should use 24x24
4) Change the size to Medium: the IDE uses 32x32 bmp

I haven't found a doc explaining the IDE change of behavior regarding component palette bitmaps loading.
Only this Delphi Tokyo article:
https://blogs.embarcadero.com/new-in-10-2-2-component-icons/

**Comment by SilverpointDev** [comment]
Added PNG glyphs to fix the IDE bugs
